config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from django_school_management.institute.models import InstituteProfile
from django_school_management.accounts.views import dashboard

admin.site.site_header = 'Django Administration'
admin.site.site_title = 'Django Site Admin'
admin.site.index_title = 'Django Administration'

DJANGO_ADMIN_URL = settings.DJANGO_ADMIN_URL + '/'
urlpatterns = [
    # admin_honeypot doesn't support Django 4
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path(DJANGO_ADMIN_URL, admin.site.urls),
    path('', include('django_school_management.pages.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('dashboard/', dashboard, name='index_view'),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('django_school_management.articles.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('account/', include('django_school_management.accounts.urls')),
    path('academics/', include('django_school_management.academics.urls')),
    path('notices/', include('django_school_management.notices.site_urls')),
    path('notices/dashboard/', include('django_school_management.notices.dashboard_urls')),
    path('students/', include('django_school_management.students.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('teachers/', include('django_school_management.teachers.urls')),
    path('result/', include('django_school_management.result.urls')),
    path('institute/', include('django_school_management.institute.urls')),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='account/password/password_reset.html'
        ),
        name="password_reset",
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='account/password/password_reset_done.html'
        ),
        name="password_reset_done",
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='account/password/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='account/password/password-reset-complete.html'
        ),
        name='password_reset_complete'
    ),
    path('dashboard/payments/', include('django_school_management.payments.urls')),
    # API URLS
    path('api/', include('django_school_management.articles.api.routes')),
    path('upload/', include('django_file_form.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls))
    ] + urlpatterns

django_school_management/teachers/urls.py
from django.urls import path
from . import views


app_name = 'teachers'

urlpatterns = [
    path('all/', views.teachers_view, name='all_teacher'),
    path('add/', views.add_teacher_view, name='add_teacher'),
    path('<int:pk>/details/', views.teacher_detail_view, name='teacher_details'),
    path('<int:pk>/update/', views.teacher_update_view.as_view(),
         name='update_teacher'),
    path('<int:pk>/delete/', views.teacher_delete_view, name='delete_teacher'),
    path('designations/', views.designation_list_view.as_view(),
         name='designations'),
    path('create/designation/', views.create_designation,
         name='create_designation')
]

django_school_management/teachers/models.py
from django.db import models
from django.conf import settings
from model_utils.models import TimeStampedModel
from taggit.managers import TaggableManager


class Designation(TimeStampedModel):
    title = models.CharField(max_length=255)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.title)


class Teacher(TimeStampedModel):
    name = models.CharField(max_length=150)
    photo = models.ImageField(upload_to='teachers',
                                default='teacheravatar.jpg')
    date_of_birth = models.DateField(blank=True, null=True)
    designation = models.ForeignKey(
        Designation,
        on_delete=models.CASCADE,
        related_name='resources'
    )
    expertise = TaggableManager(blank=True)
    mobile = models.CharField(max_length=11, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    joining_date = models.DateField(auto_now=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['joining_date', 'name']

    def __str__(self):
        return '{} ({})'.format(self.name, self.designation)

django_school_management/teachers/forms.py
from django import forms
from .models import Teacher, Designation


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['name', 'photo', 'date_of_birth',
                  'designation', 'expertise',
                  'mobile', 'email', ]
        widgets = {
            'date_of_birth': forms.TextInput({'type': 'date'}),
        }


class TeacherDesignationForm(forms.ModelForm):
    class Meta:
        model = Designation
        fields = '__all__'

django_school_management/teachers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic import UpdateView
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .models import Teacher, Designation
from .forms import TeacherForm, TeacherDesignationForm
from permission_handlers.administrative import (
    user_editor_admin_or_su,
    user_is_admin_or_su,
    user_is_teacher_or_administrative,
)
from permission_handlers.basic import user_is_verified


@user_passes_test(user_is_teacher_or_administrative)
def teachers_view(request):
    """
    :param request:
    :return: list of teachers to logged in user, login form instead.
    """
    teachers = Teacher.objects.all()
    context = {'teachers': teachers}
    return render(request, 'teachers/teacher_list.html', context)


# TODO: Reduce duplicate queries.
@user_passes_test(user_is_admin_or_su)
def add_teacher_view(request):
    """
    :param request:
    :return: teacher add form
    """
    if request.user.has_perm('create_teacher'):
        if request.method == 'POST':
            form = TeacherForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                pk = form.instance.pk
                return redirect('teachers:all_teacher')
        form = TeacherForm()
        context = {'form': form}
        return render(request, 'teachers/add_teacher.html', context)
    else:
        return render(request, 'admin_tools/permission_required.html')


@user_passes_test(user_is_verified)
def teacher_detail_view(request, pk):
    teacher = get_object_or_404(Teacher, pk=pk)
    context = {'teacher': teacher}
    return render(request, 'teachers/teacher_detail.html', context)


class teacher_update_view(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Teacher
    fields = '__all__'
    template_name = 'teachers/update_teacher.html'

    def test_func(self):
        user = self.request.user
        return user_editor_admin_or_su(user)

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            return redirect('account:profile_complete')
        return redirect('account_login')

    def get_success_url(self):
        teacher_id = self.kwargs['pk']
        return reverse_lazy('teachers:teacher_details', kwargs={'pk': teacher_id})


@user_passes_test(user_is_admin_or_su)
def teacher_delete_view(requset, pk):
    teacher = Teacher.objects.get(pk=pk)
    teacher.delete()
    return redirect('teachers:all_teacher')


@user_passes_test(user_is_admin_or_su)
def create_designation(request):
    if request.method == 'POST':
        form = TeacherDesignationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('teachers:designations')
    else:
        form = TeacherDesignationForm()
    context = {'form': form}
    return render(request, 'teachers/designation_create.html', context)


class designation_list_view(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Designation
    template_name = 'teachers/designation_list.html'

    def test_func(self):
        user = self.request.user
        return user_is_verified(user)

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            return redirect('account:profile_complete')
        return redirect('account_login')

django_school_management/teachers/templates/teachers/add_teacher.html
{% extends 'dashboard.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_header %}
  <link rel="stylesheet" href="{% static 'js/tagify/tagify.css' %}">
{% endblock %}

{% block dashboard-body %}
<form action="" method="POST" class="admission-form d-block" enctype='multipart/form-data'>
  {% csrf_token %}
  {{ form|crispy }}
  <input class="btn btn-dark float-right" type="submit" value="Save">
</form>
{% endblock %}

{% block extrajs %}
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'js/tagify/tagify.min.js' %}"></script>
  <script>
    // Select Image
    $('input[type="file"]').change(function(e){
      const fileName = e.target.files[0].name;
      $('.custom-file-label').html(fileName);
    });

    // Tagify
    const input = document.getElementById('id_expertise'),
      tagify = new Tagify( input, {duplicates: false} );

  </script>
{% endblock %}

django_school_management/teachers/templates/teachers/designation_create.html
{% extends 'dashboard.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block dashboard-body %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index_view' %}">Dashboard</a></li>
        <li class="breadcrumb-item">
            <a href="{% url 'teachers:designations' %}">Designations</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Create</li>
    </ol>
</nav>

<form action="" method="post" class="admission-form d-block">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-dark float-right" type="submit" value="Save">
</form>
{% endblock %}



{% block extrajs %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
{% endblock extrajs %}
    

django_school_management/teachers/templates/teachers/designation_list.html
{% extends 'dashboard.html' %}
{% load static %}

{% block dashboard-body %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index_view' %}">Dashboard</a></li>
        <li class="breadcrumb-item">
            <a href="{% url 'teachers:designations' %}">Designations</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">List</li>
    </ol>
</nav>


<div class="row">
    <div class="col-12 mb-2">
        <a href="{% url 'teachers:create_designation' %}" class="btn btn-success">
            Add New Designation
        </a>
    </div>
    <div class="col-12">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Designation</th>
                        <th scope="col">Resources</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                    <tr>
                        <td>{{ object.title }}</td>
                        <td>{{ object.resources.all.count }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
</div>
{% endblock %}


{% block extrajs %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
{% endblock extrajs %}
    

django_school_management/teachers/templates/teachers/teacher_detail.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
<section id="teacher-detail-section">
  <div id="teacher-detail-section--inner">
    <div class="container">
      <div class="row py-5">
        <div class="col-4">
          <img class="teacher-profile-img"
             {% if teacher.photo %}
                src="{{ teacher.photo.url }}"
             {% else %}
                {% static 'images/money.jpg' %}
             {% endif %}
            alt="" width="300" height="200">
        </div>
        <div class="col-8">
          <h2>{{ teacher.name }}</h2>
          <p></p>
          <a href="{% url 'teachers:delete_teacher' pk=teacher.pk %}" class="btn btn-danger">Delete Profile</a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

django_school_management/teachers/templates/teachers/teacher_list.html
{% extends 'dashboard.html' %}

{% block dashboard-body %}
<div class="row">
  <div class="container-fluid">
    <div class="col-8">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Designation</th>
            <th scope="col">Contact</th>
          </tr>
        </thead>
        <tbody>
          {% for teacher in teachers %}
          <tr>
            <td>{{ teacher.name }}</td>
            <td>{{ teacher.designation }}</td>
            <td>{{ teacher.mobile|default_if_none:"" }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

django_school_management/teachers/templates/teachers/update_teacher.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section id="update-teacher">
  <div id="update-teacher-inner">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-6 py-5">
          <div id="teacher-update-form">
            <form action="" method="post">
              {% csrf_token %}
              {{ form|crispy }}
              <input class="btn btn-info" type="submit" value="Update Teacher Information">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}