config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from django_school_management.institute.models import InstituteProfile
from django_school_management.accounts.views import dashboard

admin.site.site_header = 'Django Administration'
admin.site.site_title = 'Django Site Admin'
admin.site.index_title = 'Django Administration'

DJANGO_ADMIN_URL = settings.DJANGO_ADMIN_URL + '/'
urlpatterns = [
    # admin_honeypot doesn't support Django 4
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path(DJANGO_ADMIN_URL, admin.site.urls),
    path('', include('django_school_management.pages.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('dashboard/', dashboard, name='index_view'),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('django_school_management.articles.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('account/', include('django_school_management.accounts.urls')),
    path('academics/', include('django_school_management.academics.urls')),
    path('notices/', include('django_school_management.notices.site_urls')),
    path('notices/dashboard/', include('django_school_management.notices.dashboard_urls')),
    path('students/', include('django_school_management.students.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('teachers/', include('django_school_management.teachers.urls')),
    path('result/', include('django_school_management.result.urls')),
    path('institute/', include('django_school_management.institute.urls')),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='account/password/password_reset.html'
        ),
        name="password_reset",
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='account/password/password_reset_done.html'
        ),
        name="password_reset_done",
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='account/password/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='account/password/password-reset-complete.html'
        ),
        name='password_reset_complete'
    ),
    path('dashboard/payments/', include('django_school_management.payments.urls')),
    # API URLS
    path('api/', include('django_school_management.articles.api.routes')),
    path('upload/', include('django_file_form.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls))
    ] + urlpatterns

django_school_management/academics/urls.py
from django.urls import path
from . import views
from django_school_management.accounts.views import AccountListView


app_name = 'academics'

urlpatterns = [
    # Semester
    path('semesters/', views.semesters, name='all_semester'),
    path('departments/', views.departments, name='departments'),
    path('create-department/', views.create_department,
        name='create_department'
    ),
    path('create-semester/', views.create_semester,
        name='create_semester'
    ),
    path('create-academic-session/', views.create_academic_semester,
        name='create_academic_session'
    ),
    path('create-subject', views.create_subject,
        name='create_subject'
    ),
    path('depts/delete/<int:pk>/', views.delete_department, name='delete_dept'),
    path('academic_sessions/', views.academic_session, name='academic_sessions'),
    path('add_user/', views.add_user_view, name='add_user'),
    path('accounts/', AccountListView.as_view(), name='all_accounts'),
    path('department/update/<int:pk>/', views.UpdateDepartment.as_view(),
        name='update_department'),
    path('subjects/', views.subject_list, name='subject_list'),
    path('upload-subjects-csv/', views.upload_subjects_csv, name='import_subject_csv'),
]

django_school_management/academics/forms.py
from django.forms import ModelForm

from .models import Department, Semester, AcademicSession


class DepartmentForm(ModelForm):
    class Meta:
        model = Department
        fields = '__all__'
        exclude = ['created_by', ]


class SemesterForm(ModelForm):
    class Meta:
        model = Semester
        fields = '__all__'
        exclude = ['created_by', ]


class AcademicSessionForm(ModelForm):
    class Meta:
        model = AcademicSession
        fields = '__all__'
        exclude = ['created_by', ]

django_school_management/academics/views.py
import csv, io
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView
from django.urls import reverse_lazy
from rolepermissions.roles import assign_role

from .models import (Semester, Department,
    AcademicSession, Subject)
from .forms import SemesterForm, DepartmentForm, AcademicSessionForm
from django_school_management.accounts.forms import UserCreateFormDashboard
from permission_handlers.administrative import (
    user_is_admin_su_editor_or_ac_officer,
    user_editor_admin_or_su,
    user_is_teacher_or_administrative,
)
from permission_handlers.basic import user_is_verified


@login_required
def add_user_view(request):
    if request.user.has_perm('create_stuff'):
        if request.method == 'POST':
            user_form = UserCreateFormDashboard(request.POST)
            if user_form.is_valid():
                user = user_form.save()
                return redirect(
                    user.get_author_url()
                )
        else:
            user_form = UserCreateFormDashboard()
        context = {
            'user_form': user_form,
        }
        return render(request, 'academics/add_user.html', context)
    else:
        return render(request, 'academics/permission_required.html')


@user_passes_test(user_is_admin_su_editor_or_ac_officer)
def semesters(request):
    '''
    Shows semester list and 
    contains semester create form
    '''
    # TODO: Allow multiple semester creation together. (1,3,4,5) like this format.
    all_sems = Semester.objects.all()
    if request.method == 'POST':
        form = SemesterForm(request.POST)
        if form.is_valid():
            semster = form.save(commit=False)
            semster.created_by = request.user
            semster.save()
            return redirect('academics:all_semester')
    form = SemesterForm()
    ctx = {
        'all_sems': all_sems,
        'form': form,
    }
    return render(request, 'academics/all_semester.html', ctx)


@user_passes_test(user_is_admin_su_editor_or_ac_officer)
def academic_session(request):
    '''
    Responsible for academic session list view
    and academic session create view.
    '''
    if request.method == 'POST':
        form = AcademicSessionForm(request.POST)
        if form.is_valid():
            ac_session = form.save(commit=False)
            ac_session.created_by = request.user
            ac_session.save()
            return redirect('academics:academic_sessions')
    else:
        form = AcademicSessionForm()
    all_academic_session = AcademicSession.objects.all()
    ctx = {
        'form': form,
        'academic_sessions': all_academic_session,
    }
    return render(request, 'academics/academic_sessions.html', ctx)


@user_passes_test(user_is_verified)
def departments(request):
    '''
    Responsible for department list view
    and department create view.
    '''
    if request.method == 'POST':
        form = DepartmentForm(request.POST, request.FILES)
        if form.is_valid():
            dept = form.save(commit=False)
            dept.created_by = request.user
            dept.save()
            return redirect('academics:departments')
    else:
        form = DepartmentForm()
    all_department = Department.objects.all()
    ctx = {
        'form': form,
        'departments': all_department,
    }
    return render(request, 'academics/departments.html', ctx)


@user_passes_test(user_editor_admin_or_su)
def delete_semester(request, pk):
    obj = get_object_or_404(Semester, pk=pk)
    obj.delete()
    return redirect('academics:departments')


class UpdateDepartment(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Department
    form_class = DepartmentForm
    template_name = 'academics/update_department.html'
    success_url = reverse_lazy('academics:departments')

    def test_func(self):
        user = self.request.user
        return user_editor_admin_or_su(user)

    def form_valid(self, form):
        return super().form_valid(form)


@user_passes_test(user_editor_admin_or_su)
def delete_department(request, pk):
    obj = get_object_or_404(Department, pk=pk)
    obj.delete()
    return redirect('academics:departments')


@user_passes_test(user_is_teacher_or_administrative)
def upload_subjects_csv(request):
    if request.user.has_perm('create_stuff'):
        template = 'result/add_subject_csv.html'
        prompt = {
            'order': 'Subject name, Subject Code'
        }
        if request.method == 'GET':
            return render(request, template, prompt)
        
        csv_file = request.FILES['file']
        if not csv_file.name.endswith('.csv'):
            messages.error(request, 'Please, upload a CSV file.')
        try:
            data_set = csv_file.read().decode('UTF-8')
            io_string = io.StringIO(data_set)
            next(io_string)
            # TODO: upload data for foreignkey also, and
            # create object for foreignkey if no data found.
            for column in csv.reader(io_string, delimiter=',', quotechar='|'):
                _, created = Subject.objects.update_or_create(
                    name=column[0],
                    subject_code=column[1]
                )
        except:
            pass
        context = {}
        return render(request, template, context)
    else:
        return render(request, 'admin_tools/permission_required.html')


class CreateDepartmentView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Department
    fields = '__all__'
    success_url = reverse_lazy('academics:departments')
    template_name = 'academics/create_department.html'

    def test_func(self):
        user = self.request.user
        return user_editor_admin_or_su(user)

create_department = CreateDepartmentView.as_view()


class CreateSemesterView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Semester
    fields = '__all__'
    success_url = reverse_lazy('academics:all_semester')
    template_name = 'academics/create_semester.html'

    def test_func(self):
        user = self.request.user
        return user_editor_admin_or_su(user)

create_semester = CreateSemesterView.as_view()


class CreateAcademicSession(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = AcademicSession
    fields = '__all__'
    success_url = reverse_lazy('academics:academic_sessions')
    template_name = 'academics/create_academic_semester.html'

    def test_func(self):
        user = self.request.user
        return user_is_admin_su_editor_or_ac_officer(user)

create_academic_semester = CreateAcademicSession.as_view()


class SubjectListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Subject
    context_object_name = 'subjects'
    template_name = 'academics/subject_list.html'

    def test_func(self):
        user = self.request.user
        return user_is_teacher_or_administrative(user)

subject_list = SubjectListView.as_view()


class CreateSubjectView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Subject
    fields = '__all__'
    template_name = 'academics/create_subject.html'
    success_url = reverse_lazy('academics:subject_list')

    def test_func(self):
        user = self.request.user
        return user_is_teacher_or_administrative(user)

create_subject = CreateSubjectView.as_view()

templates/academics/academic_sessions.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block dashboard-body %}
<div class="row">
    <!-- SEMESTER LIST -->
    <div class="col-md-9">
        <table class="table border">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Academic Session</th>
                </tr>
            </thead>
            <tbody>
                {% for academic_session in academic_sessions %}
                <tr>
                    <td>{{ academic_session }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- SIDEBAR -->
    <div class="col-md-3">
        <ul class="list-group">
            <li class="list-group-item">
                <a href="" data-toggle="modal" data-target="#exampleModal">add new session</a>
            </li>
            <!-- Add Department Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Add New Session</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div> <!-- /modal header -->
                        <div class="modal-body">
                            <form action="" method="post">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <button type="submit" class="btn btn-outline-info float-right">
                                    Create Session
                                </button>
                            </form>
                        </div>
                        <!-- /modal body -->
                    </div>
                </div>
            </div>
        </ul>
    </div> <!-- /sidebar -->
</div>
{% endblock %}

templates/academics/add_user.html
{% extends 'dashboard.html' %} 
{% load crispy_forms_tags %} 

{% block dashboard-body %}

{% if user_form.errors %}
    {% for field in user_form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in user_form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form action="." method="post" class="admission-form d-block">
    {% csrf_token %}
    <div class="row align-items-end">
      <div class="col-6">
        <h5>User Information</h5>
        {{ user_form|crispy }}
        <h5>Permision</h5>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="user_role" id="admin-user" value="admin">
            <label class="form-check-label" for="admin-user">
                User is admin
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="user_role" id="stuff-user" value="stuff">
            <label class="form-check-label" for="stuff-user">
                User is stuff
            </label>
        </div>
      </div>
    </div>
    <button type="submit" class="btn btn-primary">Add User</button>
</form>
{% endblock %}

templates/academics/all_semester.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block dashboard-body %}
<div class="row">
  <!-- SEMESTER LIST -->
  <div class="col-md-9">
    <table class="table border">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Semester</th>
          <th scope="col">Head Teacher</th>
        </tr>
      </thead>
      <tbody>
        {% for semester in all_sems %}
        <tr>
          <td>{{ semester }}</td>
          <td>{{ semester.guide.name }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- SIDEBAR -->
  <div class="col-md-3">
    <ul class="list-group">
      <li class="list-group-item">
        <a href="" data-toggle="modal" data-target="#exampleModal">add new semester</a>
      </li>
      <!-- Add Semester Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Add New Semester</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div> <!-- /modal header -->
            <div class="modal-body">
              <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-outline-info float-right">Add Semester</button>
              </form>
            </div>
            <!-- /modal body -->
          </div>
        </div>
      </div>
    </ul>
  </div> <!-- /sidebar -->
</div>
{% endblock %}

templates/academics/departments.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block dashboard-body %}
<div class="row">
    <!-- SEMESTER LIST -->
    <div class="col-md-9">
        <table class="table border">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Department</th>
                    <th scope="col">Dept. Code</th>
                    <th scope="col">Dept. Head</th>
                    <th scope="col">Dept. Creator</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for department in departments %}
                <tr>
                    <td>{{ department.name }}</td>
                    <td>{{ department.dept_code }}</td>
                    <td>{{ department.head.name }}</td>
                    <td>{{ department.created_by }}</td>
                    <td>
                        <a class="btn btn-sm btn-danger" href="{% url 'academics:delete_dept' pk=department.id %}">
                            Delete
                        </a>
                        <a href="{% url 'academics:update_department' pk=department.pk %}" class="btn btn-sm btn-primary">
                            Update
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- SIDEBAR -->
    <div class="col-md-3">
        <ul class="list-group">
            <li class="list-group-item">
                <a href="" data-toggle="modal" data-target="#exampleModal">add new department</a>
            </li>
            <!-- Add Department Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Add New Department</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div> <!-- /modal header -->
                        <div class="modal-body">
                            <form action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <button type="submit" class="btn btn-outline-info float-right">
                                    Add Department
                                </button>
                            </form>
                        </div>
                        <!-- /modal body -->
                    </div>
                </div>
            </div>
        </ul>
    </div> <!-- /sidebar -->
</div>
{% endblock %}

templates/academics/group_list.html
{% extends 'dashboard.html' %}

{% block dashboard-body %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="#">Administrative</a></li>
        <li class="breadcrumb-item active" aria-current="page">Groups</li>
    </ol>
</nav>

<div class="row">
    <!-- groupS LIST -->
    <div class="col-md-12">
        <table class="table border">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Group Name</th>
                    <th scope="col">Users In Group</th>
                    <th scope="col">Created By</th>
                    <th scope="col">Permissions</th>
                </tr>
            </thead>
            <tbody>
                {% for group in groups %}
                <tr>
                    <td>{{ group.name }}</td>
                    <td>{{ group.user_set.all.count  }}</td>
                    <td>{{ group.group_creator }}</td>
                    <td>
                        <div class="group-table-perms">
                            {% for perm in group.permissions.all %}
                                <p>{{ perm.name }}</p>
                            {% endfor %}

                            <div class="table-td-show-more">
                                <i class="fas fa-chevron-circle-down"></i>
                            </div>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- SIDEBAR -->
    <!-- <div class="col-md-3">
        <ul class="list-group">
            <li class="list-group-item">
                <a href="#">add new group</a>
            </li>
        </ul>
    </div>  -->
    <!-- /sidebar -->
</div>
{% endblock %}

{% block extrajs %}
<script>
    // TODO: Add show more on click
    const permsTd = $('.table-td-show-more');
    // console.log(permsTd);

    const toggleHeight = (element) => {
        const currentHeight = element.style.height;
        if (currentHeight == '100%') {
            element.style.height = '100px';
        } else {
            element.style.height = '100%';
        }
    }

    permsTd.map(function(cell){
        const cellElem = permsTd[cell];
        cellElem.addEventListener('click', function(e){
            element = this.parentElement
            toggleHeight(element);
        })
    })

</script>
{% endblock %}

templates/academics/permission_required.html
{% extends 'dashboard.html' %}

{% block dashboard-body %}
<div class="alert alert-warning">
    You are not authorized for this action,<strong>please contact with administrator</strong>.
</div>
{% endblock %}

templates/academics/update_department.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block dashboard-body %}
<div class="row">
    <div class="col-md-12">
        <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Update" class="btn btn-success">
        </form>
    </div>
</div>
{% endblock %}